# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

name: SonarScan

# TODO IGNITE-20466 Investigate and fix the issue with running this workflow on PRs from forks.
on:
  workflow_run:
    workflows: [SonarBuild]
    types: [completed]

permissions:
  contents: read

#concurrency:
#  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
#  cancel-in-progress: true

jobs:
  sonarcloud:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Scan
    runs-on: ubuntu-latest
    permissions:
      actions: read
    steps:
      - name: 'Checkout project'
        if: github.event_name == 'workflow_run'
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.workflow_run.head_repository.full_name }}
          ref: ${{ github.event.workflow_run.head_branch }}
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of Sonar analysis

      - name: 'Sonar analysis'
        uses: ./.github/actions/sonar-fork
        with:
          distribution: 'temurin'
          java-version: '17'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          sonar-token: ${{ secrets.SONAR_TOKEN }}
          project-key: skorotkov_ignite
